name: "[Release] Nuget"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  push:
    name: Push to Nuget
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          # Mostly to avoid GitHub rate limiting
          extra_nix_config: |
            access-tokens = github.com=${{ github.token }}

      - name: Install Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Pack release
        run: nix develop .#ci --impure -c make pack
      - name: Publish the package to nuget.org
        run: nix develop .#ci --impure -c make release
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
